<?php
/** Easy!Appointments connection settings. */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class HMN_CRM_EasyAppointments_Settings {
	const PAGE_SLUG = 'hmn-crm-easyappointments';
	public function __construct() { add_action( 'admin_init', array( $this, 'register' ) ); add_action( 'admin_post_hmn_crm_ea_test_connection', array( $this, 'test_connection' ) ); add_action( 'admin_footer', array( $this, 'render_connection_diagnostics' ) ); }
	public function register() { register_setting( 'hmn_crm_ea_group', HMN_CRM_EasyAppointments::OPTION_NAME, array( 'type' => 'array', 'sanitize_callback' => array( $this, 'sanitize' ), 'default' => array() ) ); }
	public function sanitize( $input ) { $input = is_array( $input ) ? $input : array(); return array( 'base_url' => esc_url_raw( untrailingslashit( $input['base_url'] ?? '' ) ), 'api_key' => sanitize_text_field( $input['api_key'] ?? '' ), 'hide_provider' => empty( $input['hide_provider'] ) ? 0 : 1, 'default_provider_id' => absint( $input['default_provider_id'] ?? 0 ) ); }
	public function test_connection() { if ( ! current_user_can( 'manage_options' ) || ! check_admin_referer( 'hmn_crm_ea_test_connection' ) ) { wp_die( 'دسترسی نامعتبر است.' ); } $result = HMN_CRM_EasyAppointments::request( 'GET', 'providers', null, array( 'length' => 1 ) ); wp_safe_redirect( add_query_arg( 'hmn_ea_test', is_wp_error( $result ) ? 'failed' : 'success', admin_url( 'admin.php?page=' . self::PAGE_SLUG ) ) ); exit; }
	public function render_connection_diagnostics() {
		if ( ! current_user_can( 'manage_options' ) || self::PAGE_SLUG !== sanitize_key( wp_unslash( $_GET['page'] ?? '' ) ) ) { return; }
		$logs = HMN_CRM_EasyAppointments::connection_logs(); $test = sanitize_key( wp_unslash( $_GET['hmn_ea_test'] ?? '' ) );
		ob_start(); ?>
		<hr><h2>لاگ اتصال به موتور</h2><p>توکن و بدنهٔ درخواست در لاگ ثبت نمی‌شوند. حداکثر ۱۰۰ درخواست اخیر نگه‌داری می‌شود.</p>
		<?php if ( 'success' === $test ) : ?><div class="notice notice-success inline"><p>تست اتصال موفق بود.</p></div><?php endif; ?>
		<?php if ( 'failed' === $test ) : ?><div class="notice notice-error inline"><p>تست اتصال ناموفق بود؛ جدول زیر را بررسی کنید.</p></div><?php endif; ?>
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" style="margin:16px 0"><input type="hidden" name="action" value="hmn_crm_ea_test_connection"><?php wp_nonce_field( 'hmn_crm_ea_test_connection' ); ?><button class="button button-secondary" type="submit">تست اتصال با موتور</button></form>
		<?php if ( ! $logs ) : ?><p>هنوز لاگی ثبت نشده است.</p><?php else : ?><table class="widefat striped" style="max-width:1100px"><thead><tr><th>زمان</th><th>درخواست</th><th>HTTP</th><th>مدت</th><th>نتیجه</th></tr></thead><tbody><?php foreach ( $logs as $log ) : ?><tr><td><?php echo esc_html( $log['time'] ?? '' ); ?></td><td dir="ltr"><?php echo esc_html( ( $log['method'] ?? '' ) . ' ' . ( $log['path'] ?? '' ) ); ?></td><td><?php echo esc_html( ! empty( $log['status'] ) ? $log['status'] : '—' ); ?></td><td><?php echo esc_html( absint( $log['duration_ms'] ?? 0 ) ); ?> ms</td><td><?php echo esc_html( $log['message'] ?? '' ); ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
		<?php $html = ob_get_clean(); ?><div id="hmn-ea-connection-log"><?php echo $html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><script>(function(){var box=document.getElementById('hmn-ea-connection-log'),wrap=document.querySelector('.wrap');if(box&&wrap)wrap.appendChild(box)})();</script><?php
	}
	public static function render_page() { if ( ! current_user_can( 'manage_options' ) ) { return; } $s = HMN_CRM_EasyAppointments::settings(); ?>
<div class="wrap" dir="rtl"><h1>موتور نوبت‌دهی Easy!Appointments</h1><p>Easy!Appointments را جداگانه روی دامنه یا زیردامنهٔ امن نصب کنید، سپس در تنظیمات خود آن یک API key بسازید.</p><form method="post" action="options.php"><?php settings_fields( 'hmn_crm_ea_group' ); ?><table class="form-table"><tr><th>آدرس نصب</th><td><input required type="url" class="regular-text code" name="<?php echo esc_attr( HMN_CRM_EasyAppointments::OPTION_NAME ); ?>[base_url]" value="<?php echo esc_attr( $s['base_url'] ?? '' ); ?>" placeholder="https://appointments.example.com"><p class="description">آدرس اصلی Easy!Appointments؛ بدون /index.php/api/v1</p></td></tr><tr><th>API Key</th><td><input required type="password" class="regular-text" name="<?php echo esc_attr( HMN_CRM_EasyAppointments::OPTION_NAME ); ?>[api_key]" value="<?php echo esc_attr( $s['api_key'] ?? '' ); ?>" autocomplete="new-password"></td></tr><tr><th>نمایش پزشک در فرم</th><td><label><input type="checkbox" name="<?php echo esc_attr( HMN_CRM_EasyAppointments::OPTION_NAME ); ?>[hide_provider]" value="1" <?php checked( ! empty( $s['hide_provider'] ) ); ?>> برای مجموعهٔ تک‌پزشکی مخفی شود</label></td></tr><tr><th>پزشک پیش‌فرض</th><td><input type="number" min="1" name="<?php echo esc_attr( HMN_CRM_EasyAppointments::OPTION_NAME ); ?>[default_provider_id]" value="<?php echo esc_attr( $s['default_provider_id'] ?? '' ); ?>"><p class="description">شناسهٔ Provider در Easy!Appointments؛ وقتی فیلد پزشک مخفی است الزامی است.</p></td></tr><tr><th>فرم سایت</th><td><code>[hmn_booking_form]</code><p class="description">این shortcode را در برگهٔ نوبت‌دهی قرار دهید.</p></td></tr></table><?php submit_button( 'ذخیرهٔ اتصال' ); ?></form></div>
<?php }
}
new HMN_CRM_EasyAppointments_Settings();
